tap "felixkratz/formulae"
tap "nikitabobko/tap"

brew "atuin"
brew "bat"
brew "felixkratz/formulae/borders"
brew "fd"
brew "fzf"
brew "git-delta"
brew "helix"
brew "herdr"
brew "hunk"
brew "starship"
brew "zsh-autosuggestions"
brew "zoxide"

cask "nikitabobko/tap/aerospace"
cask "ghostty"
