format = """
$directory\
$git_branch\
$character"""

add_newline = false
scan_timeout = 10

[directory]
truncation_length = 3
style = "yellow dimmed"

[git_branch]
style = "purple dimmed"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
