[theme]
name = "catppuccin"
auto_switch = false

[theme.custom]
panel_bg = "#161616"
surface0 = "#1C1C1C"
surface1 = "#282828"
surface_dim = "#161616"
overlay0 = "#595959"
overlay1 = "#A0A0A0"
text = "#FFFFFF"
subtext0 = "#A0A0A0"
accent = "#FFC799"
mauve = "#FBADFF"
green = "#99FFE4"
yellow = "#FFC799"
red = "#FF8080"
blue = "#FFC799"
teal = "#99FFE4"
peach = "#FFC799"

[ui]
accent = "#FFC799"
